services:
  transactions-api:
    build:
      context: .
      args:
        requirements_file: requirements.txt
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - mongodb
    env_file: .env
    restart: always
    networks:
      - transactions-network

  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_DB_NAME: ${MONGO_INITDB_ROOT_DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      - transactions-network


networks:
  transactions-network:
    driver: bridge

volumes:
  mongo_data: